# Google App Engine configuration for backend
runtime: nodejs18

# Environment variables
env_variables:
  NODE_ENV: "production"

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65

# Health check
health_check:
  enable_health_check: true
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

# Resources
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
